# Generated by Django 5.0.3 on 2024-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postlabel',
            field=models.CharField(blank=True, choices=[('POPULAR', 'popular'), ('TRENDING', 'Trending'), ('FEATURED', 'Featured'), ('TOP_RATED', 'Top Rated'), ('BEST_SELLING', 'Best Selling'), ('VIRAL', 'Viral')], max_length=100, null=True),
        ),
    ]
