# Generated by Django 5.0.6 on 2024-05-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
